language: java
jdk:
 - oraclejdk8

test_coverage:
- mvn clean test jacoco:report coveralls:report

install:
- mvn install -DskipTests=true -Dspring.profiles.active=test -Dmaven.javadoc.skip=true -B -V